name: Deno Build and Publishing

on:
  push:
    branches: '*'

jobs:
  builddeno:
    name: Build Deno Application
    runs-on: ubuntu-latest
    container: denoland/deno:alpine-2.4.2
    
    steps:
      - uses: actions/checkout@v4

      - name: Show Deno version
        run: deno --version
         
      - name: Check
        run: deno task check

  publish:

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    name: publishin to JSR
    runs-on: ubuntu-latest
    container: denoland/deno:alpine-2.4.2

    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
         
      - name: releasing
        run: deno publish id-token= ${{ secrets.PUBLISH_TO_JSR }}